### ISSUE TITLE
admin-user-home vs admin_user_home

### ISSUE THREAD

**Issue by acurrieclark** [konstruktoid/hardening#100]
https://github.com/konstruktoid/hardening/blob/47246cfcb18d6139e12ef9d68a39b5cafd9fe7d8/misc/audit-base.rules#L7

I am struggling with an issue where my audit.log is getting overloaded on a new server I am hardening.

In a previous version of this file, `admin-user-home` (hyphenated) was written as `admin_user_home` (underscored). I can't find any reference as to why this might be, and wondered if this might be in error?

Many thanks

**Comment by konstruktoid** [comment]
Hi @acurrieclark, that was changed in https://github.com/konstruktoid/hardening/commit/e0af71f93ce4a8ccba0e391990b902a3079368fa approx 13 months ago.
Since https://github.com/konstruktoid/hardening/blob/master/misc/audit.header#L5-L6 flushes all rules before applying the new ones, the old key shouldn't be present.

**Comment by acurrieclark** [comment]
Ah, I am sorry, I just misunderstood the meaning of the key. Thanks for getting back to me.
